name: "SOOS DAST Scan"

on:
  push:
    branches: [ "main" ]

jobs:
  soos:
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@1217f3bb7ae38735dd78803b79bba8d32643e77e
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "dast-githubActions-28"
           api_url: "https://qa-api.soos.io/api/"
           target_url: "https://brokencrystals.com/"
           disableRules: 10003,10010,10011,10020,10021,10110

