name: "SOOS DAST Scan"

on:
  push:
    branches: [ "main" ]

jobs:
  soos:
    permissions:
      security-events: write # for uploading code scanning alert info
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@1217f3bb7ae38735dd78803b79bba8d32643e77e 
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "dast-githubActions-27"
           api_url: "https://qa-api.soos.io/api/"
           target_url: "https://brokencrystals.com/"
           output_format: 'sarif'
           other_options: "-d"
           #disable_rules: 10003,10010,10011,10020,10021,10110
           image_tag: beta
      - name: Upload SOOS DAST SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
           
           

